//! LettaBot `lettabot.yaml` generation from bears + membership (Phase 1).
//!
//! Slack/WhatsApp `allowedUsers` are left empty — operators fill IDs by hand until
//! external identity mapping exists.

use serde::Serialize;

use crate::errors::CustomError;

use super::db::LettaBotRow;

#[derive(Serialize)]
struct Root {
    server: ServerSection,
    agents: Vec<AgentEntry>,
}

#[derive(Serialize)]
struct ServerSection {
    letta: LettaServer,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct LettaServer {
    /// Env-style placeholder; never embed the real Letta admin secret.
    api_key: String,
    base_url: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct AgentEntry {
    name: String,
    agent_id: String,
    channels: Channels,
}

#[derive(Serialize)]
struct Channels {
    slack: ChannelUsers,
    whatsapp: ChannelUsers,
}

#[derive(Serialize)]
struct ChannelUsers {
    #[serde(rename = "allowedUsers")]
    allowed_users: Vec<String>,
}

/// Build YAML for LettaBot. One `agents[]` entry per `(user, bear)` membership where the bear
/// has a Letta agent id.
pub fn render_lettabot_yaml(letta_base_url: &str, rows: &[LettaBotRow]) -> Result<String, CustomError> {
    let base_url = if letta_base_url.trim().is_empty() {
        "http://bears-letta:8283"
    } else {
        letta_base_url.trim_end_matches('/')
    };

    let mut agents: Vec<AgentEntry> = rows
        .iter()
        .filter_map(|r| {
            let agent_id = r.letta_agent_id.as_deref()?.to_string();
            Some(AgentEntry {
                name: entry_name(&r.username, &r.bear_slug),
                agent_id,
                channels: Channels {
                    slack: ChannelUsers {
                        allowed_users: vec![],
                    },
                    whatsapp: ChannelUsers {
                        allowed_users: vec![],
                    },
                },
            })
        })
        .collect();

    agents.sort_by(|a, b| a.name.cmp(&b.name));

    let doc = Root {
        server: ServerSection {
            letta: LettaServer {
                api_key: "${LETTA_SERVER_PASS}".to_string(),
                base_url: base_url.to_string(),
            },
        },
        agents,
    };

    let body = serde_yaml::to_string(&doc)
        .map_err(|e| CustomError::Parsing(format!("lettabot yaml serialize: {e}")))?;

    Ok(format!(
        "# Generated by Den (BEARS). LettaBot talks to Letta directly in v1.\n\
         # Replace allowedUsers with Slack user IDs (e.g. U0123) and WhatsApp E.164 numbers.\n\
         # apiKey uses env substitution — match your Letta server admin password / API key.\n\
         \n\
         {body}"
    ))
}

fn entry_name(username: &str, bear_slug: &str) -> String {
    let u = slug_token(username);
    let u = if u.is_empty() { "user".to_string() } else { u };
    format!("{u}--{bear_slug}")
}

fn slug_token(s: &str) -> String {
    let mut out = String::new();
    let mut prev_sep = true;
    for c in s.to_lowercase().chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c);
            prev_sep = false;
        } else if !prev_sep {
            out.push('-');
            prev_sep = true;
        }
    }
    out.trim_matches('-').to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::bears::db::LettaBotRow;

    #[test]
    fn render_includes_server_and_agents() {
        let rows = vec![
            LettaBotRow {
                username: "alice".to_string(),
                bear_slug: "house".to_string(),
                letta_agent_id: Some("agent-abc".to_string()),
            },
            LettaBotRow {
                username: "bob".to_string(),
                bear_slug: "house".to_string(),
                letta_agent_id: None,
            },
        ];
        let y = render_lettabot_yaml("http://letta:8283", &rows).unwrap();
        assert!(y.contains("http://letta:8283"));
        assert!(y.contains("${LETTA_SERVER_PASS}"));
        assert!(y.contains("agent-abc"));
        assert!(y.contains("alice--house"));
        assert!(!y.contains("bob--house"));
        assert!(y.contains("apiKey"));
        assert!(y.contains("baseUrl"));
        assert!(y.contains("allowedUsers"));
    }

    #[test]
    fn placeholder_base_when_unconfigured() {
        let y = render_lettabot_yaml("", &[]).unwrap();
        assert!(y.contains("bears-letta:8283"));
    }
}
